"""guest home: tagline, cover, Wi-Fi, opening hours

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 06:39:17.643179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('tagline', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('restaurant_settings', sa.Column('cover', sa.String(length=64), nullable=True))
    op.add_column('restaurant_settings', sa.Column('wifi_name', sa.String(length=64), nullable=True))
    op.add_column('restaurant_settings', sa.Column('wifi_password', sa.String(length=64), nullable=True))
    op.add_column('restaurant_settings', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'opening_hours')
    op.drop_column('restaurant_settings', 'wifi_password')
    op.drop_column('restaurant_settings', 'wifi_name')
    op.drop_column('restaurant_settings', 'cover')
    op.drop_column('restaurant_settings', 'tagline')
    # ### end Alembic commands ###
