"""telegram: staff chat settings

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-25 15:29:34.304597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('telegram_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('restaurant_settings', sa.Column('telegram_bot_token', sa.String(length=128), nullable=True))
    op.add_column('restaurant_settings', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_settings', 'telegram_chat_id')
    op.drop_column('restaurant_settings', 'telegram_bot_token')
    op.drop_column('restaurant_settings', 'telegram_enabled')
    # ### end Alembic commands ###
