"""service calls: service_call, table.opened_at

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-25 15:10:28.831529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('waiter', 'bill', name='call_type'), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'card', 'qr', name='payment_method'), nullable=True),
    sa.Column('status', sa.Enum('open', 'taken', name='call_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('taken_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['table_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taken_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_call_created_at'), 'service_call', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_call_session_id'), 'service_call', ['session_id'], unique=False)
    op.create_index(op.f('ix_service_call_status'), 'service_call', ['status'], unique=False)
    op.create_index(op.f('ix_service_call_table_id'), 'service_call', ['table_id'], unique=False)
    op.add_column('table', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'opened_at')
    op.drop_index(op.f('ix_service_call_table_id'), table_name='service_call')
    op.drop_index(op.f('ix_service_call_status'), table_name='service_call')
    op.drop_index(op.f('ix_service_call_session_id'), table_name='service_call')
    op.drop_index(op.f('ix_service_call_created_at'), table_name='service_call')
    op.drop_table('service_call')
    for name in ('call_status', 'payment_method', 'call_type'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
