"""order language: the menu language a guest ordered in

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-25 18:52:02.814061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('language', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_order_language'), 'order', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_language'), table_name='order')
    op.drop_column('order', 'language')
    # ### end Alembic commands ###
