"""orders: order, order_item, order_item_modifier

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 14:42:58.186109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'cooking', 'served', 'closed', 'rejected', name='order_status'), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['table_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_session_id'), 'order', ['session_id'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_table_id'), 'order', ['table_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('price_id', sa.Integer(), nullable=True),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_id'], ['item_price.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_table('order_item_modifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('modifier_id', sa.Integer(), nullable=True),
    sa.Column('group_name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modifier_id'], ['modifier.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_modifier_order_item_id'), 'order_item_modifier', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_modifier_order_item_id'), table_name='order_item_modifier')
    op.drop_table('order_item_modifier')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_table_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_session_id'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    sa.Enum(name='order_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
