"""guest sessions: table_session, settings.logo

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 14:06:43.694771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_session_table_id'), 'table_session', ['table_id'], unique=False)
    op.add_column('restaurant_settings', sa.Column('logo', sa.String(length=64), nullable=True))
    op.drop_column('restaurant_settings', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant_settings', sa.Column('logo_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('restaurant_settings', 'logo')
    op.drop_index(op.f('ix_table_session_table_id'), table_name='table_session')
    op.drop_table('table_session')
    # ### end Alembic commands ###
